name: Generator

on:
  workflow_dispatch:
    inputs:
      account:
        description: 'Number of Accounts (default = 0)'
        required: false
        default: '0'
      key:
        description: 'Number of Keys (default = 1)'
        required: false
        default: '1'
      mail:
        description: 'Mail provider for license'
        required: true
        type: choice
        options:
          - 1secmail
          - guerrillamail
          - developermail
          - mailticking
          - fakemail
          - inboxes
          - incognitomail
        default: fakemail
      key_type:
        description: 'License type'
        required: true
        type: choice
        options:
          - --key
          - --small-business-key
          - --vpn-codes
        default: --key
      telegram_token:
        description: 'Telegram Bot Token'
        required: true
        type: string
      telegram_chat_id:
        description: 'Telegram Chat ID'
        required: true
        type: string

jobs:
  Windows:
    runs-on: windows-latest
    steps:
      - name: Generate key
        shell: pwsh
        run: |
          [int]$ACCOUNT = ${{ github.event.inputs.account }}
          [int]$KEY = ${{ github.event.inputs.key }}
          $MAIL = "${{ github.event.inputs.mail }}"
          $KEY_TYPE = "${{ github.event.inputs.key_type }}"
          $TELEGRAM_TOKEN = "${{ github.event.inputs.telegram_token }}"
          $TELEGRAM_CHAT_ID = "${{ github.event.inputs.telegram_chat_id }}"

          git clone https://github.com/ashhub683/bye-bye.git ESET-KeyGen
          cd ESET-KeyGen

          pip install -r ./file/requirements.txt

          if ($ACCOUNT -gt 0 -and $KEY -gt 0) {
            python main.py --auto-detect-browser --account --email-api $MAIL --skip-update-check --no-logo --disable-progress-bar --disable-logging --token $TELEGRAM_TOKEN --chat_id $TELEGRAM_CHAT_ID --repeat $ACCOUNT
            python main.py --auto-detect-browser $KEY_TYPE --email-api $MAIL --skip-update-check --no-logo --disable-progress-bar --disable-logging --token $TELEGRAM_TOKEN --chat_id $TELEGRAM_CHAT_ID --repeat $KEY
            "Account:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            Get-Content -Path ./*ACCOUNTS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            "`nKey:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            Get-Content -Path ./*KEYS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          elseif ($ACCOUNT -gt 0) {
            python main.py --auto-detect-browser --account --email-api $MAIL --skip-update-check --no-logo --disable-progress-bar --disable-logging --token $TELEGRAM_TOKEN --chat_id $TELEGRAM_CHAT_ID --repeat $ACCOUNT
            "`nAccount:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            Get-Content -Path ./*ACCOUNTS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
          elseif ($KEY -gt 0) {
            python main.py --auto-detect-browser $KEY_TYPE --email-api $MAIL --skip-update-check --no-logo --disable-progress-bar --disable-logging --token $TELEGRAM_TOKEN --chat_id $TELEGRAM_CHAT_ID --repeat $KEY
            "`nKey:" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
            Get-Content -Path ./*KEYS.txt | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
          }
